# Generated by Django 4.1.7 on 2023-03-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_id',
            field=models.IntegerField(default=0),
        ),
    ]
