# Generated by Django 4.1.7 on 2023-03-20 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_post_author_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='First_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Last_name',
        ),
    ]
